# -*- coding: utf-8 -*-
"""Reference content shipped with the app: pregnancy weeks, milestone types,
community groups and the starter recipe library."""

# (week, size_label, emoji, length_cm, weight_g, summary, tip)
PREGNANCY_WEEKS = [
    (4, "a poppy seed", "\u26AB", 0.1, 0.4, "The embryo implants and the placenta begins to form.", "A test will read positive around now. Start a folic acid supplement if you haven't."),
    (5, "an apple seed", "\U0001F34E", 0.2, 0.5, "The neural tube, which becomes the brain and spine, is closing.", "Early nausea is common. Small, frequent meals help more than large ones."),
    (6, "a lentil", "\U0001F7E4", 0.4, 0.8, "A heartbeat can often be detected on an early scan.", "Book your first antenatal visit."),
    (7, "a blueberry", "\U0001FAD0", 1.0, 1.0, "Arm and leg buds appear; the face begins to take shape.", "Fatigue peaks around now. Rest without guilt."),
    (8, "a raspberry", "\U0001F353", 1.6, 1.5, "Fingers and toes are forming and the heart has four chambers.", "Keep hydrated \u2014 it eases nausea and headaches."),
    (9, "a grape", "\U0001F347", 2.3, 2.0, "The embryo is now called a fetus. Tiny muscles begin to work.", "Gentle movement like walking helps circulation."),
    (10, "a kumquat", "\U0001F34A", 3.1, 4.0, "Vital organs are formed and starting to function.", "If nausea stops food entirely, speak to your clinician."),
    (11, "a fig", "\U0001F338", 4.1, 7.0, "The head is about half the body length; fingernails appear.", "Many people feel their energy returning soon."),
    (12, "a lime", "\U0001F34B", 5.4, 14.0, "Reflexes develop \u2014 fingers can curl, toes can flex.", "The first-trimester scan usually happens this week."),
    (13, "a pea pod", "\U0001FAD8", 7.4, 23.0, "Vocal cords form. Second trimester begins.", "Risk of miscarriage drops sharply from here."),
    (14, "a lemon", "\U0001F34B", 8.7, 43.0, "Baby can squint, frown and suck a thumb.", "A good week to start a stretch-mark routine if you want one."),
    (15, "an apple", "\U0001F34F", 10.1, 70.0, "Bones are hardening; baby can sense light through the womb.", "Sleep on your side rather than your back from around now."),
    (16, "an avocado", "\U0001F951", 11.6, 100.0, "Facial muscles work \u2014 expressions begin.", "You may feel the first flutters, especially if this isn't your first."),
    (17, "a turnip", "\U0001FAD1", 13.0, 140.0, "Fat stores begin forming under the skin.", "Try pelvic floor exercises daily \u2014 they matter later."),
    (18, "a bell pepper", "\U0001FAD1", 14.2, 190.0, "Baby can hear \u2014 your voice and heartbeat are the soundtrack.", "Talk or sing to your bump. They're listening."),
    (19, "a mango", "\U0001F96D", 15.3, 240.0, "A protective coating called vernix forms on the skin.", "Leg cramps are common. Stretch calves before bed."),
    (20, "a banana", "\U0001F34C", 25.6, 300.0, "Halfway. The anomaly scan usually happens this week.", "Ask for a printout \u2014 it's a lovely first photo for the memory book."),
    (21, "a carrot", "\U0001F955", 26.7, 360.0, "Baby swallows amniotic fluid and tastes what you eat.", "Kicks get stronger and more regular."),
    (22, "a papaya", "\U0001FAD0", 27.8, 430.0, "Eyebrows and eyelashes appear; grip is developing.", "Backache starts for many. Support your lower back when sitting."),
    (23, "a grapefruit", "\U0001F34A", 28.9, 501.0, "Hearing is sharp enough to recognise familiar voices.", "Some babies respond to music with a kick."),
    (24, "a cantaloupe", "\U0001F348", 30.0, 600.0, "Lungs develop branches; the inner ear is fully formed.", "Baby now has a real chance of survival if born early."),
    (25, "a cauliflower", "\U0001F966", 34.6, 660.0, "Baby is putting on fat and looking less wrinkled.", "Glucose screening usually happens between now and week 28."),
    (26, "a lettuce", "\U0001F96C", 35.6, 760.0, "Eyes begin to open for the first time.", "Count kicks daily from around now."),
    (27, "a cabbage", "\U0001F955", 36.6, 875.0, "Regular sleep and wake cycles begin. Third trimester starts.", "You may notice hiccup rhythms \u2014 they're normal."),
    (28, "an aubergine", "\U0001F346", 37.6, 1005.0, "Baby can blink and may dream.", "Antenatal visits usually become fortnightly now."),
    (29, "a butternut squash", "\U0001F383", 38.6, 1150.0, "Bones are fully developed but still soft.", "Iron and calcium needs rise. Ask about supplements."),
    (30, "a large cabbage", "\U0001F96C", 39.9, 1320.0, "Baby's grip is strong; hair may be growing.", "Heartburn is common. Eat earlier in the evening."),
    (31, "a coconut", "\U0001F965", 41.1, 1500.0, "All five senses are working.", "Practise your breathing techniques."),
    (32, "a squash", "\U0001F383", 42.4, 1700.0, "Baby usually turns head-down around now.", "Pack a hospital bag \u2014 earlier than you think you need to."),
    (33, "a pineapple", "\U0001F34D", 43.7, 1920.0, "The skull stays soft to ease the journey out.", "Braxton Hicks contractions become noticeable."),
    (34, "a melon", "\U0001F348", 45.0, 2150.0, "Lungs are nearly mature.", "Discuss your birth preferences with your clinician."),
    (35, "a honeydew", "\U0001F348", 46.2, 2380.0, "Baby is running out of room; movements feel like rolls.", "Rest when you can \u2014 sleep gets harder from here."),
    (36, "a romaine lettuce", "\U0001F96C", 47.4, 2620.0, "Baby may drop lower into the pelvis.", "Weekly antenatal visits usually start."),
    (37, "a bunch of chard", "\U0001F96C", 48.6, 2860.0, "Considered early term. Baby practises breathing.", "Know the signs of labour and when to call."),
    (38, "a leek", "\U0001F9C5", 49.8, 3080.0, "The brain and lungs keep maturing right to the end.", "Nesting energy is real. Don't overdo it."),
    (39, "a small pumpkin", "\U0001F383", 50.7, 3290.0, "Full term. Baby is ready.", "Keep your bag and documents by the door."),
    (40, "a small watermelon", "\U0001F349", 51.2, 3460.0, "Your due date \u2014 though most babies pick their own.", "Only about 1 in 20 arrive exactly on the due date."),
    (41, "a watermelon", "\U0001F349", 51.7, 3600.0, "Still cooking. Extra monitoring usually begins.", "Your clinician will discuss options for induction."),
    (42, "a pumpkin", "\U0001F383", 52.0, 3700.0, "Post-term. Baby will be closely monitored.", "Almost there. Rest and stay in close contact with your clinic."),
]

MILESTONE_TYPES = [
    ("positive_test", "Positive test", "\u2728", "pregnancy", 1),
    ("first_scan", "First scan", "\U0001FA7B", "pregnancy", 2),
    ("heard_heartbeat", "Heard the heartbeat", "\U0001F49F", "pregnancy", 3),
    ("first_kick", "First kick", "\U0001F463", "pregnancy", 4),
    ("anomaly_scan", "20-week scan", "\U0001FA7B", "pregnancy", 5),
    ("baby_shower", "Baby shower", "\U0001F381", "pregnancy", 6),
    ("nursery_ready", "Nursery ready", "\U0001F6CF", "pregnancy", 7),
    ("birth", "Birth day", "\U0001F476", "baby", 10),
    ("first_smile", "First smile", "\U0001F60A", "baby", 11),
    ("first_laugh", "First laugh", "\U0001F602", "baby", 12),
    ("rolled_over", "Rolled over", "\U0001F504", "baby", 13),
    ("first_tooth", "First tooth", "\U0001F9B7", "baby", 14),
    ("sat_up", "Sat up alone", "\U0001FA91", "baby", 15),
    ("first_food", "First solid food", "\U0001F963", "baby", 16),
    ("first_crawl", "First crawl", "\U0001F9CE", "baby", 17),
    ("first_word", "First word", "\U0001F5E3", "baby", 18),
    ("pulled_to_stand", "Pulled to stand", "\U0001F9CD", "baby", 19),
    ("first_steps", "First steps", "\U0001F45F", "baby", 20),
    ("first_birthday", "First birthday", "\U0001F382", "baby", 21),
    ("first_haircut", "First haircut", "\u2702\uFE0F", "baby", 22),
]

GROUPS = [
    ("first-time-parents", "First-time parents", "\U0001F476", "Everything nobody warned you about."),
    ("due-this-year", "Due this year", "\U0001F5D3", "Find your due-date buddies."),
    ("weaning", "Weaning & feeding", "\U0001F963", "Purees, baby-led weaning, fussy eaters."),
    ("sleep", "Sleep", "\U0001F31B", "Naps, night wakings, and surviving both."),
    ("nairobi-parents", "Nairobi parents", "\U0001F1F0\U0001F1EA", "Local clinics, classes and recommendations."),
    ("working-parents", "Working parents", "\U0001F4BC", "Maternity leave, childcare, and the juggle."),
]

RECIPES = [
    ("Simple sweet potato puree", "puree", 6, 25, "\U0001F360",
     "Naturally sweet and gentle on new tummies. A good first food.",
     ["1 medium sweet potato, peeled and cubed", "60 ml breast milk or formula"],
     ["Steam the sweet potato for 15 minutes until very soft.",
      "Blend with the milk until completely smooth.",
      "Cool to lukewarm and check the temperature on your wrist before serving."], []),
    ("Avocado and banana mash", "puree", 6, 5, "\U0001F951",
     "No cooking needed. Creamy, filling and full of healthy fats.",
     ["1/2 ripe avocado", "1/2 ripe banana"],
     ["Mash both together with a fork until smooth.",
      "Add a splash of milk if it's too thick.",
      "Serve straight away \u2014 it browns quickly."], []),
    ("Butternut and lentil mash", "puree", 7, 30, "\U0001F383",
     "Iron and protein from lentils, sweetness from squash.",
     ["150 g butternut squash, cubed", "3 tbsp red lentils, rinsed", "200 ml water"],
     ["Simmer the lentils in the water for 15 minutes.",
      "Add the squash and cook 10 minutes more until both are soft.",
      "Blend to your baby's preferred texture."], []),
    ("Soft-cooked carrot sticks", "finger_food", 7, 20, "\U0001F955",
     "Perfect for baby-led weaning \u2014 soft enough to gum, firm enough to hold.",
     ["2 large carrots, cut into thick finger-length sticks"],
     ["Steam the sticks for 12\u201315 minutes until soft enough to squash between your fingers.",
      "Cool completely before offering.",
      "Always stay with your baby while they eat."], []),
    ("Banana oat pancakes", "finger_food", 8, 15, "\U0001F95E",
     "Three ingredients, no added sugar. Freezes well.",
     ["1 ripe banana", "40 g oats", "1 egg"],
     ["Blend everything to a batter.",
      "Cook small spoonfuls in a lightly oiled pan for 2 minutes each side.",
      "Cool and cut into strips."], ["egg", "gluten"]),
    ("Chicken and vegetable stew", "toddler", 9, 40, "\U0001F372",
     "A gentle, unsalted family stew that scales up easily.",
     ["150 g chicken thigh, diced", "1 carrot, diced", "1 small potato, diced",
      "1/2 onion, finely chopped", "300 ml unsalted stock"],
     ["Soften the onion in a little oil.",
      "Add the chicken and brown lightly.",
      "Add the vegetables and stock, then simmer 25 minutes.",
      "Mash or chop to suit your child, and check for bones."], []),
    ("Creamy spinach and potato mash", "puree", 7, 25, "\U0001F966",
     "An easy way into greens \u2014 the potato mellows the spinach.",
     ["1 potato, peeled and cubed", "large handful of spinach", "2 tbsp full-fat yoghurt"],
     ["Boil the potato for 15 minutes until tender.",
      "Add the spinach for the final 2 minutes.",
      "Drain, then mash with the yoghurt."], ["dairy"]),
    ("Uji (millet porridge)", "puree", 6, 20, "\U0001F963",
     "A Kenyan staple first porridge, thinned for young babies.",
     ["3 tbsp millet or sorghum flour", "300 ml water", "60 ml milk"],
     ["Whisk the flour into cold water until there are no lumps.",
      "Bring to a simmer, stirring constantly, for 10 minutes.",
      "Stir in the milk and cool before serving."], ["dairy"]),
    ("Mashed pumpkin and coconut", "puree", 7, 25, "\U0001F383",
     "Mildly sweet with a silky finish from coconut milk.",
     ["200 g pumpkin, cubed", "3 tbsp coconut milk"],
     ["Steam the pumpkin for 15 minutes until soft.",
      "Mash with the coconut milk until smooth."], []),
    ("Scrambled egg fingers", "finger_food", 8, 10, "\U0001F95A",
     "Firm scrambled egg cut into strips \u2014 easy to grip.",
     ["2 eggs", "1 tbsp whole milk"],
     ["Beat the eggs with the milk.",
      "Cook gently in a non-stick pan until fully set and firm.",
      "Cool, then slice into finger-width strips."], ["egg", "dairy"]),
    ("Apple and pear puree", "puree", 6, 20, "\U0001F34F",
     "A classic two-fruit blend. Freezes into perfect portions.",
     ["1 apple, peeled and cubed", "1 pear, peeled and cubed", "50 ml water"],
     ["Simmer both fruits in the water for 12 minutes until soft.",
      "Blend until smooth, adding cooking liquid to loosen."], []),
    ("Fish and potato mash", "toddler", 10, 30, "\U0001F41F",
     "Gentle white fish with soft potato. Check very carefully for bones.",
     ["1 white fish fillet", "1 potato, peeled and cubed", "1 tbsp butter"],
     ["Boil the potato for 15 minutes.",
      "Steam the fish for 8 minutes until it flakes easily.",
      "Flake the fish, checking twice for bones, and mash with the potato and butter."],
     ["fish", "dairy"]),
]
